services:
  - type: web
    name: WIZARD.MD
    env: node
    branch: main
    repo: https://github.com/shamika28/WIZARD-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: STATUS_VIEW_SEEN
        value: true
      - key: MODE
        value: public
      - key: AUTO_REACT
        value: false
